### ISSUE TITLE
[7월 29일 ~ 8월 4일] 이규호, 최원섭 KHUHACKER Main Contents TODO

### ISSUE THREAD

**Issue by unpo88** [unpo88/KHUHACKER#2]
KHUHACKER Main Contents

- [ ] Main화면 Contents 온라인으로 회의 후 결정
- [ ] 결정된 Contents 기본 뼈대 작성
- [ ] 기본 뼈대 개발 문서 작성(간략히)
- [ ] Wiki 및 공지사항 등 Sub Page 구성

**Comment by unpo88** [comment]
@GyuhoLee 는 개인적으로 한 주간 진행하면 좋을 것 같은 내용을
Issue로 등록해보고, Project에 연동해보길 바람

**Comment by unpo88** [comment]
@GyuhoLee 내일 시간내서 만나자

**Comment by unpo88** [comment]
navbar, footer, content 하나 완성
