### ISSUE TITLE
[10월 9일 ~ 10월 13일] 이규호, 최원섭, 김다희, 김명락 KHUHACKER Open TODO #2

### ISSUE THREAD

**Issue by unpo88** [unpo88/KHUHACKER#7]
#KHUHACKER Open

- [x] 이규호 문서화작업 및 서버 세팅
- [x] 김다희, 이규호 주소록/임원진 페이지 작성
- [x] 김명락 Jekyll Notice 문서화작업
- [x] 추후 진행 상황 공유
